[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = ".env"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
flow_testnet = "${FLOW_TESTNET_RPC}"
flow = "${FLOW_RPC}"

[wallet]
private_key = "${PRIVATE_KEY}"
